### PR TITLE
Display the tab switcher in a popup

### LINKED ISSUE #17: Popup in a separate window takes considerable time to load
It takes the browser considerable time to load the popup with the switcher in a separate browser window — up to a second. A user cannot start typing immediately after starting the extension, and has to wait till the window is rendered.

### PR DESCRIPTION
**Pull request by dmitry-timofeev**
## Overview 

Starting a new browser window takes considerable
time (up to a second), making the user wait till
it is rendered. Extension popups, however, are
displayed way faster.

Also, extension popups work better in multi-monitor
setup.

Fixes #17, #16

### CODE REVIEW

**Comment by dmitry-timofeev** [comment]
@tapapax , 
I don’t have much JavaScript experience, please review carefully :slightly_smiling_face:

**Comment by tapapax** [comment]
This popup version is really cool.
There is only one unpleasant behavior though - in case if I have many (34 in my case) tabs open, popup is initially scrolled a bit:
default

I think that something like this is additionally required: https://github.com/tapapax/firefox-fts/commit/9ce50d02ec86f045b0e5c4635c7a610e98e5e745.

**Comment by dmitry-timofeev** [comment]
Awesome, thank you!

**Comment by tapapax** [comment]
2.3.0 is already available in AMO 👍

**Pull request merged**
